### ISSUE TITLE
是否考虑支持ts？

### ISSUE THREAD

**Issue by renmu123** [dream2023/vue-ele-form-image-uploader#2]
我是前端新手，项目是用ts写的，在导入这个插件后发现编译会报错
按照提示以及一番搜索后创建了`vue-ele-form-image-uploader.d.ts`文件写入`declare module 'vue-ele-form-image-uploader'`但是还是会报错

**希望该插件能原生支持ts导入**

**Comment by dream2023** [comment]
1、新建一个的 package.d.ts（任意名字的.d.ts）
```js
declare module "vue-ele-form-image-uploader";
```

2、shims-vue.d.ts

```js
declare module "*.vue" {
  import Vue from "vue";
  export default Vue;
}

declare module "*.ejs" {
  let str: string;
  export default str;
}
```
